name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "lean-argparse"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "main"
